# -*- coding: utf-8 -*-
"""DesafioPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18-ZXJkxNBI8NqF5dn__o77uWHGwcRhbl
"""

import random

def trofeuTop():
  print("------PRÊMIO TOP!!!------")
  print("------------------------")
  print("      .-=========-. ")
  print("      \'-=======-'/ ")
  print("      _|   .=.   |_ ")
  print("     ((|  {{1}}  |)) ")
  print("      \|   /|\   |/ ")
  print("       \__ '`' __/ ")
  print("         _`) (`_ ")
  print("         _`) (`_ ")
  print("       _/_______\_ ")
  print("      /___________\ ")
  print("------------------------")

def trofeuMedio():

  print("------PRÊMIO MÉDIO------")
  print("------------------------")
  print("         {}")
  print("        /__\ ")
  print("      /|    |\ ")
  print("     (_|    |_) ")
  print("        \  /")
  print("         )(")
  print("       _|__|_")
  print("     _|______|_")
  print("    |__________|")
  print("------------------------")

def campeao(giro):

    trofeuTop()
    print(giro)
    print("------------------------------------------")

def quaseCampeao(giro):

    trofeuMedio()
    print(giro)
    print("------------------------------------------")

def perdeu(giro):

    print("*******************************************")
    print("******************PERDEU******************")
    print(giro)
    print("*******************************************")

def gira(frutas):

  girando = random.choices(frutas, k = 4)

  frutaDuplicadas = []

  cred = 0

  frutaEnvia = []

  for i in girando:

    if(girando.count(i) == 4):

      frutaDuplicadas.append(i)

    elif(girando.count(i) > 1 and girando[0] == girando[1]):

      if(i not in frutaDuplicadas):

        frutaDuplicadas.append(i)

  qtdFrutas = len(frutaDuplicadas)

  if(qtdFrutas == 2):

    cred = 2
    quaseCampeao(girando)
    frutaEnvia = frutaDuplicadas

  elif(qtdFrutas == 4):

    cred = 4
    frutaEnvia = frutaDuplicadas
    campeao(girando)

  else:

    cred = 0
    frutaEnvia = girando
    perdeu(girando)

  return cred, frutaEnvia

frutas = ["caju", "manga", "ciriguela", "cajarana", "pitomba", "carambola", "jaca", "pinha"]

credito = 0
cred = 0

print("------------------------------------------")
print("------------INICIANDO OS JOGOS------------")
print("------------------------------------------")

credito = int(input("Adicione um valor: "))

print("------------------------------------------")
print("CREDITO - {}".format(credito))
print("1 -> Start")
print("2 -> Sair")
print("------------------------------------------")

op = int(input("Gira?"))

while(op != 2 and credito > 0):

  if(op == 1):

    verifica = gira(frutas)[0] #valor

    if(verifica == 0):

      #perdeu(gir)

      cred = - 1

    elif(verifica == 4):

      #campeao(gir)

      cred = 10000000000000000000000000000000

    else:

      #quaseCampeao(gir)

      cred = 5000

  credito = credito + cred

  if(credito == 0):

    print("Perdeu tudo tururururururururu );")
    break

  print("CREDITO = {}".format(credito))
  op = int(input("Gira?"))